package site.dogether.presentation

enum class Screen {
    SPLASH,
    FORCE_UPDATE,
    ON_BOARDING,
    PARTICIPATION_METHOD,
    CREATE_GROUP,
    GROUP_CREATED,
    PARTICIPATE_GROUP,
    GROUP_PARTICIPATED,
    ERROR,
    HOME,
    MY_PAGE,
    STATISTICS,
    CERTIFICATION_LIST,
    SETTINGS,
    GROUP_MANAGEMENT
}