[versions]
version-code = "1"
version-name = "1.1.0"

accompanistPermissions = "0.37.3"
agp = "8.11.1"
firebaseBom = "34.7.0"
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"

# AndroidX / Compose
coreKtx = "1.16.0"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2025.07.00"

# Orbit
orbit = "10.0.0"

# Navigation
navigation = "2.9.2"

# Koin
koin = "4.1.0"

# Kotest
kotest = "5.9.1"

# Mockk
mockk = "1.13.8"

# Coroutines
coroutines = "1.10.2"

# Konsist
konsist = "0.17.3"

# Ktor
ktor = "3.2.3"

# Coil
coil = "2.7.0"
jetbrainsKotlinJvm = "2.2.0"

# Kakao
kakao = "2.21.6"

# Datastore
datastore = "1.1.7"

#Chottulink
chottuLink = "1.0.9"

#gms
gms = "4.4.4"

[libraries]
# AndroidX / Compose
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

# Orbit
orbit-compose = { group = "org.orbit-mvi", name = "orbit-compose", version.ref = "orbit" }
orbit-viewmodel = { group = "org.orbit-mvi", name = "orbit-viewmodel", version.ref = "orbit" }

# Navigation
navigation-runtime = { group = "androidx.navigation", name = "navigation-runtime-android", version.ref = "navigation" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

# Koin
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }

# Kotest
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { group = "io.kotest", name = "kotest-framework-engine", version.ref = "kotest" }

# Mockk
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

# Coroutines
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

# Kotlin reflect
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

# Ktor test
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }

# Konsist
konsist = { group = "com.lemonappdev", name = "konsist", version.ref = "konsist" }

# Chottulink
chottulink-sdk = { module = "com.chottulink:android-sdk", version.ref = "chottuLink" }

# Ktor
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization = { group = "io.ktor", name = "ktor-client-serialization", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }

# Coil
coil-base = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

# Kakao
kakao = { group = "com.kakao.sdk", name = "v2-user", version.ref = "kakao" }

# Datastore
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# Firebase / GMS
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
gms = { id = "com.google.gms.google-services", version.ref = "gms" }

[bundles]
compose-core = [
    "androidx-core-ktx",
    "androidx-lifecycle-runtime-ktx",
    "androidx-activity-compose",
    "androidx-ui",
    "androidx-ui-graphics",
    "androidx-ui-tooling-preview",
    "androidx-material3"
]

compose-debug = [
    "androidx-ui-tooling",
    "androidx-ui-test-manifest"
]

compose-test = [
    "androidx-ui-test-junit4"
]

orbit = [
    "orbit-compose",
    "orbit-viewmodel"
]

navigation = [
    "navigation-runtime",
    "navigation-compose"
]

kotest = [
    "kotest-runner-junit5",
    "kotest-assertions-core",
    "kotest-framework-engine",
    "kotlin-reflect"
]

koin = [
    "koin-core",
    "koin-android",
    "koin-androidx-compose"
]

ktor = [
    "ktor-client-core",
    "ktor-client-cio",
    "ktor-client-content-negotiation",
    "ktor-client-serialization",
    "ktor-serialization-kotlinx-json",
    "ktor-client-logging",
    "ktor-client-auth"
]

coil = [
    "coil-base",
    "coil-compose"
]